name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Type check
        run: yarn typecheck

      - name: Run ESLint
        run: yarn lint

      - name: Run tests
        run: yarn run test:ci

      - name: Build
        run: yarn build
        env:
          # Add any required environment variables for build
          NEXT_PUBLIC_SITE_URL: https://pse.dev
          NODE_ENV: test
